# ----------------------------
# Makefile Options
# ----------------------------

NAME = trinome
ICON = icon.png
DESCRIPTION = "antiseche + resolveur de racines"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
