# ----------------------------
# Makefile Options
# ----------------------------

NAME = SCALAIRE
ICON = icon.png
DESCRIPTION = "antiseche fait avec ce toolchain"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
