# ----------------------------
# Makefile Options
# ----------------------------

NAME = PROBA
ICON = icon.png
DESCRIPTION = "antiseche proba"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
