# ----------------------------
# Makefile Options
# ----------------------------

NAME = EXPON
ICON = icon.png
DESCRIPTION = "antiseche exponentiel"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
